# Use for development purposes.  Building on top of base Dockerfile that is published

version: '3'
services:
  heatmap:
    container_name: heatmap
    image: seasketch/heatmap:latest
    build:
      context: .
      target: workspace
    volumes:
    # Mount repo, overriding default work space
    - .:/work
    # Mount test project
    - ./projects:/projects
    command: ["bash"]